app/Http/routes.php
<?php

Route::group(['middleware' => 'web'], function () {
    Route::auth();

    /*Route::any('register', function() {
        return redirect()->route('index');
    });*/

    Route::get('/', ['as' => 'index', 'uses' => 'PagesController@index']);
    Route::get('/saving', 'PagesController@saving');
    Route::get('/admin', 'PagesController@admin');
    Route::get('/contact', 'PagesController@contact');
    Route::post('/contact', 'PagesController@sendMail');
    Route::get('/about', 'PagesController@about');
    Route::get('/search', 'PagesController@search');
    Route::post('/search', ['as' => 'search', 'uses' => 'PagesController@postSearch']);

    Route::resource('properties', 'PropertiesController');

    Route::post('properties/{id}/photos', 'PropertiesController@addPhoto');

    Route::get('properties/{id}/rightMove', ['as' => 'properties.rm', 'uses' => 'PropertiesController@rightMove']);
    Route::get('properties/{id}/removeRightMove', ['as' => 'properties.rrm', 'uses' => 'PropertiesController@removeRightMove']);
    Route::get('
    RightMove', ['as' => 'properties.rmp', 'uses' => 'PropertiesController@rightmoveProperties']);

    Route::delete('photos/{id}', 'PagesController@destroyPhoto');

    Route::get('review/pending', ['as' => 'review.pending', 'uses' => 'ReviewsController@pending']);
    Route::get('review/{id}/accept', ['as' => 'review.accept', 'uses' => 'ReviewsController@accept']);
    Route::resource('review', 'ReviewsController');
   Route::get('rooms/{id}/create', ['as' => 'rooms.create', 'uses' => 'RoomsController@create']);
   Route::post('rooms/{id}/create', ['as' => 'rooms.store', 'uses' => 'RoomsController@store']);
});

resources/views/admin.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <h1 class="page-heading">
            Admin Controls
        </h1>
        <div class="panel panel-default">
            <div class="panel-body">
                <ul>
                    <li><a href="{{route('properties.create')}}">Add a property</a></li>
                    <li><a href="{{route('review.pending')}}">Evaluate pending reviews {{$reviews}}</a></li>
                </ul>
            </div>
        </div>
    </div>
@stop

resources/views/home.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row">
        <div class="col-md-10 col-md-offset-1">
            <div class="panel panel-default">
                <div class="panel-heading">Dashboard</div>

                <div class="panel-body">
                    You are logged in!
                </div>
            </div>
        </div>
    </div>
</div>
@endsection