app/Http/routes.php
<?php

Route::group(['middleware' => 'web'], function () {
    Route::auth();

    /*Route::any('register', function() {
        return redirect()->route('index');
    });*/

    Route::get('/', ['as' => 'index', 'uses' => 'PagesController@index']);
    Route::get('/saving', 'PagesController@saving');
    Route::get('/admin', 'PagesController@admin');
    Route::get('/contact', 'PagesController@contact');
    Route::post('/contact', 'PagesController@sendMail');
    Route::get('/about', 'PagesController@about');
    Route::get('/search', 'PagesController@search');
    Route::post('/search', ['as' => 'search', 'uses' => 'PagesController@postSearch']);

    Route::resource('properties', 'PropertiesController');

    Route::post('properties/{id}/photos', 'PropertiesController@addPhoto');

    Route::get('properties/{id}/rightMove', ['as' => 'properties.rm', 'uses' => 'PropertiesController@rightMove']);
    Route::get('properties/{id}/removeRightMove', ['as' => 'properties.rrm', 'uses' => 'PropertiesController@removeRightMove']);
    Route::get('
    RightMove', ['as' => 'properties.rmp', 'uses' => 'PropertiesController@rightmoveProperties']);

    Route::delete('photos/{id}', 'PagesController@destroyPhoto');

    Route::get('review/pending', ['as' => 'review.pending', 'uses' => 'ReviewsController@pending']);
    Route::get('review/{id}/accept', ['as' => 'review.accept', 'uses' => 'ReviewsController@accept']);
    Route::resource('review', 'ReviewsController');
   Route::get('rooms/{id}/create', ['as' => 'rooms.create', 'uses' => 'RoomsController@create']);
   Route::post('rooms/{id}/create', ['as' => 'rooms.store', 'uses' => 'RoomsController@store']);
});

app/Http/Controllers/ReviewsController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\CreateReviewRequest;
use App\Review;
use App\User;
use Illuminate\Database\Eloquent\ModelNotFoundException;
use Illuminate\Http\Request;
use Illuminate\Database\Eloquent\ModelNotFoundException as ModelNotFound;

use App\Http\Requests;

class ReviewsController extends Controller
{
    /**
     * ReviewsController constructor.
     */
    public function __construct()
    {
        $this->middleware('auth', ['except' => ['index', 'create', 'store']]);
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $reviews = Review::where('live','yes')->get();

        return view('reviews.index', compact('reviews'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('reviews.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param CreateReviewRequest|Request $request
     * @return \Illuminate\Http\Response
     */
    public function store(CreateReviewRequest $request)
    {
        $data = $request->except('rating');
        $data += ['live' => 'no'];

        $review = Review::create($data);

        $user = User::first();

        $rating = $review->rating(['rating' => $request->get('rating')], $user);


        flash()->success('Success', 'You have submitted a review.');

        return redirect()->back();
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $review = Review::destroy($id);

        flash()->success('Success!', 'You have deleted that review');

        return redirect()->back();
    }

    public function pending()
    {
        $reviews = Review::where('live','no')->get();

        return view('reviews.pending', compact('reviews'));
    }

    public function accept($id)
    {
        $review = Review::where('id',$id)->where('live', 'no')->update(['live' => 'yes']);


        flash()->success('Success', 'You have made that review live!');
        return redirect()->back();
    }
}

resources/views/reviews/create.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <h2 class="page-heading">Write a review</h2>
        <form action="{{route('review.store')}}" class="form-horizontal" method="post">
            {!! csrf_field() !!}
            <div class="form-group">
                <label for="name" class="col-sm-2 control-label">Name</label>
                <div class="col-sm-10">
                    <input type="text" name="name" class="form-control" id="name" placeholder="Name">
                </div>
            </div>
            <div class="form-group">
                <label for="email" class="col-sm-2 control-label">Email</label>
                <div class="col-sm-10">
                    <input type="email" name="email" class="form-control" id="email" placeholder="Email">
                </div>
            </div>
            <div class="form-group">
                <label for="review" class="col-sm-2 control-label">Review</label>
                <div class="col-sm-10">
                    <textarea name="review" class="form-control" id="review" rows="7"></textarea>
                </div>
            </div>
            <div class="form-group">
                <label for="rating" class="col-sm-2 control-label">Rating</label>
                <div class="col-sm-10">
                    <div class="stars">
                        <input class="star star-5" id="star-5" type="radio" name="rating" value="5"/>
                        <label class="star star-5" for="star-5"></label>
                        <input class="star star-4" id="star-4" type="radio" name="rating" value="4"/>
                        <label class="star star-4" for="star-4"></label>
                        <input class="star star-3" id="star-3" type="radio" name="rating" value="3"/>
                        <label class="star star-3" for="star-3"></label>
                        <input class="star star-2" id="star-2" type="radio" name="rating" value="2"/>
                        <label class="star star-2" for="star-2"></label>
                        <input class="star star-1" id="star-1" type="radio" name="rating" value="1"/>
                        <label class="star star-1" for="star-1"></label>
                    </div>
                </div>
            </div>
            <div class="form-group col-sm-10 col-sm-offset-5">
                <button type="submit" class="btn btn-primary">Submit Review</button>
            </div>
        </form>
    </div>
@stop

resources/views/reviews/index.blade.php
@extends('layouts.app')

@section('content')

    <div class="container">
        <div style="height: 390px;">
            <a href="{{route('review.create')}}" class="btn btn-warning pull-right">Submit Review</a>
            <h2 class="page-heading">Customer reviews.</h2>
        </div>
        @foreach($reviews as $review)
            <div class="panel panel-default">
                <div class="panel-heading">
                    @if(auth()->check())
                        <a href="{{route('review.edit', ['id' => $review->id])}}"></a>
                        <form action="{{route('review.destroy', ['id' => $review->id])}}" method="post">
                            {!! csrf_field() !!}
                            <input type="hidden" name="_method" value="DELETE">
                            <button class="pull-right delete-button" type="submit">
                                <i class="fa fa-times" aria-hidden="true"></i>
                            </button>
                        </form>
                    @endif
                    <h3 class="panel-title">Review By {{$review->name}}</h3>
                </div>
                <div class="panel-body reviews">
                    <p>{{$review->review}}</p>
                    <ul class="stars">
                        <li @if($review->ratings()->first()->rating > 0) class="checked" @endif></li>
                        <li @if($review->ratings()->first()->rating > 1) class="checked" @endif></li>
                        <li @if($review->ratings()->first()->rating > 2) class="checked" @endif></li>
                        <li @if($review->ratings()->first()->rating > 3) class="checked" @endif></li>
                        <li @if($review->ratings()->first()->rating > 4) class="checked" @endif></li>
                    </ul>
                </div>
            </div>
        @endforeach
    </div>

@stop

resources/views/reviews/pending.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <h2 class="page-heading">Pending Reviews</h2>
    </div>
            @forelse($reviews->chunk(4) as $chunk)
                <div class="row full-width-white">
                    <div class="container">
                        @foreach($chunk as $review)
                                <div class="property-box col-md-3">
                                    <p class="property-box-price">
                                        {{$review->review}}
                                    </p>

                                    <a href="{{route('review.accept', ['id' => $review->id])}}">
                                        <div class="tick"></div>
                                    </a>
                                    <form action="{{route('review.destroy', ['id' => $review->id])}}" method="post">
                                        {!! csrf_field() !!}
                                        <input type="hidden" name="_method" value="DELETE">
                                        <button type="submit" name="submit" class="cross">
                                        <!--<div class="cross"></div>-->
                                        </button>
                                    </form>
                                </div>
                        @endforeach
                    </div>
                </div>
            @empty
                <div class="container">
                    <h2>There are no pending reviews</h2>
                </div>
            @endforelse
        </div>
    </div>
@stop