app/Http/routes.php
<?php

Route::group(['middleware' => 'web'], function () {
    Route::auth();

    /*Route::any('register', function() {
        return redirect()->route('index');
    });*/

    Route::get('/', ['as' => 'index', 'uses' => 'PagesController@index']);
    Route::get('/saving', 'PagesController@saving');
    Route::get('/admin', 'PagesController@admin');
    Route::get('/contact', 'PagesController@contact');
    Route::post('/contact', 'PagesController@sendMail');
    Route::get('/about', 'PagesController@about');
    Route::get('/search', 'PagesController@search');
    Route::post('/search', ['as' => 'search', 'uses' => 'PagesController@postSearch']);

    Route::resource('properties', 'PropertiesController');

    Route::post('properties/{id}/photos', 'PropertiesController@addPhoto');

    Route::get('properties/{id}/rightMove', ['as' => 'properties.rm', 'uses' => 'PropertiesController@rightMove']);
    Route::get('properties/{id}/removeRightMove', ['as' => 'properties.rrm', 'uses' => 'PropertiesController@removeRightMove']);
    Route::get('
    RightMove', ['as' => 'properties.rmp', 'uses' => 'PropertiesController@rightmoveProperties']);

    Route::delete('photos/{id}', 'PagesController@destroyPhoto');

    Route::get('review/pending', ['as' => 'review.pending', 'uses' => 'ReviewsController@pending']);
    Route::get('review/{id}/accept', ['as' => 'review.accept', 'uses' => 'ReviewsController@accept']);
    Route::resource('review', 'ReviewsController');
   Route::get('rooms/{id}/create', ['as' => 'rooms.create', 'uses' => 'RoomsController@create']);
   Route::post('rooms/{id}/create', ['as' => 'rooms.store', 'uses' => 'RoomsController@store']);
});

app/Property.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Property extends Model
{

    protected $fillable = [
        'number',
        'street',
        'town',
        'code1',
        'code2',
        'bedrooms',
        'reception',
        'gardens',
        'parking',
        'type',
        'description',
        'price',
        'state',
        'rightMove'
    ];

    public function scopeLocatedAt($query, $number, $street, $city)
    {
        $street = str_replace('-', ' ', $street);

        return $query->where(compact($number, $street, $city))->first();

    }

    /*public function getPriceAttribute($price)
    {
        return '&pound;'. number_format($price);
    }*/

    public function photos()
    {
        return $this->hasMany(Photo::class);
    }

    public function rooms()
    {
        return $this->hasMany(Room::class);
    }
}

app/Http/Controllers/PropertiesController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\PropertyRequest;
use App\Photo;
use App\Property;
use App\Room;
use Frozensheep\RightmoveADF\RightmoveADF;
use Frozensheep\RightmoveADF\Values\Channels;
use Frozensheep\RightmoveADF\Values\MediaTypes;
use Frozensheep\RightmoveADF\Values\PropertyTypes;
use Frozensheep\RightmoveADF\Values\Statuses;
use Illuminate\Http\Request;

use App\Http\Requests;
use Illuminate\Support\Facades\Storage;
use Image;

use App\Events\PropertyAdded;

class PropertiesController extends Controller
{
    /**
     * PropertiesController constructor.
     */
    public function __construct()
    {
        $this->middleware('auth', ['except' => ['index','show']]);
    }


    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $properties = Property::with('photos')->orderBy('created_at', 'desc')->get();

        return view('properties.index', compact('properties'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('properties.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param PropertyRequest|Request $request
     * @return \Illuminate\Http\Response
     */
    public function store(PropertyRequest $request)
    {

        $data = Property::create($request->all());

        //event(new PropertyAdded($data));

        flash()->success('Success', 'The property has been added.');

        return redirect()->route('rooms.create', ['id' => $data->id]);
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $property = Property::with('rooms')->findOrFail($id);

        return view('properties.show', compact('property'));
    }

    public function addPhoto($id, Request $request)
    {
        $this->validate($request, [
            'photo' => 'required|mimes:jpg,jpeg,png,bmp'
        ]);

        $file = $request->file('photo');

        $name = time() . $file->getClientOriginalName();
        $thumbnail_path = "img/properties/photos/tn-{$name}";

        $file->move('img/properties/photos', $name);

        $property = Property::findOrFail($id);

        $property->photos()->create(['name' => $name, 'path' => "img/properties/photos/{$name}", 'thumbnail_path' => $thumbnail_path]);

        Image::make("img/properties/photos/{$name}")->fit(200)->save($thumbnail_path);

        return 'done';
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $property = Property::findOrFail($id);

        return view('properties.edit', compact('property'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $data = Property::findOrFail($id);
        $data ->update($request->all());

        flash()->success('Success', 'You have successfully updated the property.');

        return redirect()->route('properties.show', ['id' => $data->id]);
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {

        $rooms = Room::where('property_id', $id)->get();
        $photos = Photo::where('property_id', $id)->get();
        $property = Property::findOrFail($id);

        if($property->rightMove != '')
        {
            flash()->error('Error!', 'You must remove the property from rightmove before you delete it from the website.');
            return redirect()->route('properties.show', ['id' => $id]);
        }
        foreach($rooms as $room)
        {

            $room->delete();
        }

        foreach($photos as $photo)
        {
            Storage::delete([$photo->path, $photo->thumbnail_path]);
            $photo->delete();
        }

        $property->delete();

        flash()->success('Success', 'You have removed that property.');

        return redirect()->route('properties.index');
    }

    public function rightMove($id)
    {
        $property = Property::with('photos', 'rooms')->findOrFail($id);

        $objRightmoveADF = new RightmoveADF(app_path(env('ADF_CERT')), env('ADF_CERT_PASS'), RightmoveADF::TEST);

        $objRequest = $objRightmoveADF->createRequest(RightmoveADF::SendProperty);


        $objRequest->network->network_id = intval(env('ADF_NETWORK_ID'));
        $objRequest->branch->branch_id = intval(env('ADF_BRANCH_ID'));
        $objRequest->branch->channel = Channels::Sales;
        $objRequest->property->agent_ref = $id;

        $objRequest->property->published = true;
        $objRequest->property->property_type = $this->getPropertyTypes($property->type);
        $objRequest->property->status = $this->getStatus($property->state);

        $number = $objRequest->property->address->house_name_number = (string)$property->number;
        $street = $objRequest->property->address->address_2 = $property->street;
        $town = $objRequest->property->address->town = $property->town;
        $post1 = $objRequest->property->address->postcode_1 = $property->code1;
        $post2 = $objRequest->property->address->postcode_2 = $property->code2;
        $objRequest->property->address->display_address = $number . ' ' . $street . ' ' . $town . ' ' . $post1. ' ' .$post2;
        $objRequest->property->price_information->price = $property->price;

        $objRequest->property->details->summary = substr($property->description, 0, 100);
        $objRequest->property->details->description = $property->description;
        $objRequest->property->details->bedrooms = (int)$property->bedrooms;
        $objRequest->property->details->reception_rooms = (int)$property->reception;
        $objRequest->property->details->parking()[] = $this->getParkingTypes($property->parking);


        $i = 0;
        $j = 0;
        $room = null;
        $media = null;
        foreach ($property->rooms as $roomobj) {
            $i++;
            ${'room' . $i} = $objRequest->property->details->rooms()->create();
            ${'room' . $i}->room_name = $roomobj->name;
            ${'room' . $i}->room_description = $roomobj->desc;
            ${'room' . $i}->room_length = $roomobj->length;
            ${'room' . $i}->room_width = $roomobj->width;
            ${'room' . $i}->room_dimension_unit = $this->getUnits($roomobj->unit);
        }

        foreach($property->photos as $photo)
        {
            $j++;
            ${'media' . $j} = $objRequest->property->media()->create();
            ${'media' . $j}->media_type = MediaTypes::Image;
            $photoUrl = 'http://leversonpalmer.co.uk/'.$photo->path;
            ${'media' . $j}->media_url = $photoUrl;
        }

        $objRequest->property->principal->principal_email_address = 'rpalmer@leversonpalmer.com';
        $objRequest->property->principal->auto_email_when_live = true;
        $objRequest->property->principal->auto_email_updates = true;


        $objResponse = $objRightmoveADF->send($objRequest);

        if($objResponse->success) {
            $property->rightMove = $objResponse->property->rightmove_url;
            $property->save();
            flash()->success('Success', 'Property has been added to RightMove!');
            return redirect()->route('properties.show', ['id' => $id]);
        } else {
            print_r($objResponse->errors);
        }

    }

    public function removeRightMove($id)
    {
        $property = Property::findOrFail($id);
        $objRightmoveADF = new RightmoveADF(app_path(env('ADF_CERT')), env('ADF_CERT_PASS'), RightmoveADF::TEST);

        $objRequest = $objRightmoveADF->createRequest(RightmoveADF::RemoveProperty);

        $objRequest->network->network_id = intval(env('ADF_NETWORK_ID'));
        $objRequest->branch->branch_id = intval(env('ADF_BRANCH_ID'));
        $objRequest->branch->channel = Channels::Sales;
        $objRequest->property->agent_ref = $id;

        $objResponse = $objRightmoveADF->send($objRequest);

        if($objResponse->success) {
            $property->rightMove = '';
            $property->save();
            flash()->success('Success', 'The property has successfully been removed from rightmove.');
            return redirect()->route('properties.show', ['id' => $id]);
        } else {
            print_r($objResponse->errors);
        }
    }

    private function getPropertyTypes($type)
    {
        switch($type) {
            case 'DetachedHouse':
                return 4;
            break;
            case 'SemiDetachedHouse':
                return 3;
            break;
            case 'TerracedHouse':
                return 1;
            break;
            case 'Flat':
                return 8;
            break;
        }
    }

    private function getParkingTypes($type)
    {
        switch($type) {
            case 'Allocated':
                return 13;
            break;
            case 'Communal':
                return 14;
            break;
            case 'Covered':
                return 15;
            break;
            case 'Garage':
                return 16;
            break;
            case 'Driveway':
                return 17;
            break;
            case 'Gated':
                return 18;
            break;
            case 'OffStreet':
                return 19;
            break;
            case 'Onstreet':
                return 20;
            break;
            case 'Rear':
                return 21;
            break;
            case 'Permit':
                return 22;

resources/views/properties/create.blade.php
@extends('layouts.app')

@section('content')

    <div class="container">
        <h1 class="page-heading">Selling your Home?</h1>

        <form action="{{route('properties.store')}}" method="post" enctype="multipart/form-data">
            <div class="row">
                <div class="col-md-6">
                    {!! csrf_field() !!}
                    <div class="form-group">
                        <label for="number">House number: </label>
                        <input type="number" name="number" id="number" class="form-control" value="{{old('number')}}" required>
                    </div>

                    <div class="form-group">
                        <label for="street">Street: </label>
                        <input type="text" name="street" id="street" class="form-control" value="{{old('street')}}" required>
                    </div>

                    <div class="form-group">
                        <label for="city">Town: </label>
                        <input type="text" name="town" id="town" class="form-control" value="{{old('town')}}" required>
                    </div>

                    <div class="form-group">
                        <label for="code">Post Code (1st half): </label>
                        <input type="text" name="code1" id="code1" class="form-control" value="{{old('code1')}}" required>
                    </div>
                    <div class="form-group">
                        <label for="code">Post Code (2nd half): </label>
                        <input type="text" name="code2" id="code2" class="form-control" value="{{old('code2')}}" required>
                    </div>

                    <div class="form-group">
                        <label for="bedrooms">Number of Bedrooms: </label>
                        <input type="number" name="bedrooms" id="bedrooms" class="form-control" value="{{old('bedrooms')}}" required>
                    </div>
                    <div class="form-group">
                        <label for="reception">Reception Rooms: </label>
                        <input type="number" name="reception" id="reception" class="form-control" value="{{old('reception')}}" required>
                    </div>
                    <div class="form-group">
                        <label for="state">State: </label>
                        <select name="state" id="state" class="form-control" required>
                            <option value="Available">For Sale</option>
                            <option value="UnderOffer">Under Offer</option>
                        </select>
                    </div>
                </div>
                <div class="col-md-6">
                    <div class="form-group">
                        <label for="gardens">Gardens: </label>
                        <input type="number" name="gardens" id="gardens" class="form-control" value="{{old('gardens')}}" required>
                    </div>
                    <div class="form-group">
                        <label for="parking">Parking: </label>
                        <select name="parking" id="parking" class="form-control" required>
                            <option value="Allocated">Allocated</option>
                            <option value="Communal">Communal</option>
                            <option value="Covered">Covered</option>
                            <option value="Driveway">Driveway</option>
                            <option value="Garage">Garage</option>
                            <option value="Gated">Gated</option>
                            <option value="Offstreet">Off Street</option>
                            <option value="Onstreet">On Street</option>
                            <option value="Permit">Permit</option>
                            <option value="PrivateParking">Private</option>
                            <option value="Rear">Rear</option>
                            <option value="Residents">Residents</option>
                        </select>
                    </div>

                    <div class="form-group">
                        <label for="type">Type: </label>
                        <select name="type" id="type" class="form-control" required>
                            <option value="DetachedHouse">Detached</option>
                            <option value="SemiDetachedHouse">Semi Detached</option>
                            <option value="TerracedHouse">Terraced</option>
                            <option value="Flat">Flat</option>
                        </select>
                    </div>
                    <div class="form-group">
                        <label for="price">Sale Price: (&pound;)</label>
                        <input type="number" name="price" id="price" class="form-control" value="{{old('price')}}" required>
                    </div>

                    <div class="form-group">
                        <label for="description">Description: </label>
                        <textarea name="description" id="description" class="form-control" rows="10" required>
                            {{old('description')}}
                        </textarea>
                    </div>

                    <div class="form-group">
                        <label for="rightMove" class="control-label">Rightmove URL</label>
                        <input type="text" name="rightMove" class="form-control" id="rightMove" placeholder="Rightmove URL">
                    </div>

                </div>
                <div class="col-md-12">
                    <div class="form-gorup">
                        <button type="submit" class="btn btn-primary">Sell Home</button>
                    </div>
                </div>
            </div>
        </form>

        @if (count($errors) > 0)
            <div class="alert alert-danger" role="alert">
                <ul>
                    @foreach($errors->all() as $error)
                        <li>{{$error}}</li>
                    @endforeach
                </ul>
            </div>
        @endif
    </div>

@stop

@section('scripts')
    <script>
        $('#roomNames').pillbox();
    </script>
@endsection

resources/views/properties/edit.blade.php
@extends('layouts.app')

@section('content')

    <div class="container">
        <h1 class="page-heading">Edit {{$property->street}}</h1>

        <form action="{{route('properties.update', ['id' => $property->id])}}" method="post">
            <input type="hidden" name="_method" value="PATCH">
            <div class="row">
                <div class="col-md-6">
                    {!! csrf_field() !!}
                    <div class="form-group">
                        <label for="number">House number: </label>
                        <input type="number" name="number" id="number" class="form-control" value="{{old('number', $property->number)}}" required>
                    </div>

                    <div class="form-group">
                        <label for="street">Street: </label>
                        <input type="text" name="street" id="street" class="form-control" value="{{old('street', $property->street)}}" required>
                    </div>

                    <div class="form-group">
                        <label for="city">Town: </label>
                        <input type="text" name="town" id="town" class="form-control" value="{{old('town', $property->town)}}" required>
                    </div>

                    <div class="form-group">
                        <label for="code">Post Code (1st half): </label>
                        <input type="text" name="code1" id="code1" class="form-control" value="{{old('code1', $property->code1)}}" required>
                    </div>
                    <div class="form-group">
                        <label for="code">Post Code (2nd half): </label>
                        <input type="text" name="code2" id="code2" class="form-control" value="{{old('code2', $property->code2)}}" required>
                    </div>

                    <div class="form-group">
                        <label for="bedrooms">Number of Bedrooms: </label>
                        <input type="number" name="bedrooms" id="bedrooms" class="form-control" value="{{old('bedrooms', $property->bedrooms)}}" required>
                    </div>
                    <div class="form-group">
                        <label for="reception">Reception Rooms: </label>
                        <input type="number" name="reception" id="reception" class="form-control" value="{{old('reception', $property->reception)}}" required>
                    </div>
                    <div class="form-group">
                        <label for="state">State: </label>
                        <select name="state" id="state" class="form-control" required>
                            <option value="Available">For Sale</option>
                            <option value="UnderOffer">Under Offer</option>
                        </select>
                    </div>
                </div>
                <div class="col-md-6">
                    <div class="form-group">
                        <label for="gardens">Gardens: </label>
                        <input type="number" name="gardens" id="gardens" class="form-control" value="{{old('gardens', $property->gardens)}}" required>
                    </div>
                    <div class="form-group">
                        <label for="parking">Parking: </label>
                        <select name="parking" id="parking" class="form-control" required>
                            <option value="Allocated">Allocated</option>
                            <option value="Communal">Communal</option>
                            <option value="Covered">Covered</option>
                            <option value="Driveway">Driveway</option>
                            <option value="Garage">Garage</option>
                            <option value="Gated">Gated</option>
                            <option value="Offstreet">Off Street</option>
                            <option value="Onstreet">On Street</option>
                            <option value="Permit">Permit</option>
                            <option value="PrivateParking">Private</option>
                            <option value="Rear">Rear</option>
                            <option value="Residents">Residents</option>
                        </select>
                    </div>

                    <div class="form-group">
                        <label for="type">Type: </label>
                        <select name="type" id="type" class="form-control" required>
                            <option value="DetachedHouse">Detached</option>
                            <option value="SemiDetachedHouse">Semi Detached</option>
                            <option value="TerracedHouse">Terraced</option>
                            <option value="Flat">Flat</option>
                        </select>
                    </div>
                    <div class="form-group">
                        <label for="price">Sale Price: (&pound;)</label>
                        <input type="number" name="price" id="price" class="form-control" value="{{old('price', $property->price)}}" required>
                    </div>

                    <div class="form-group">
                        <label for="description">Description: </label>
                        <textarea name="description" id="description" class="form-control" rows="10" required>
                            {{old('description', $property->description)}}
                        </textarea>
                    </div>

                    <div class="form-group">
                        <label for="rightMove" class="control-label">Rightmove URL</label>
                        <input type="text" name="rightMove" class="form-control" id="rightMove" value="{{old('rightMove', $property->rightMove)}}" placeholder="Rightmove URL">
                    </div>

                </div>
                <div class="col-md-12">
                    <div class="form-gorup">
                        <button type="submit" class="btn btn-primary">Update Home</button>
                    </div>
                </div>
            </div>
        </form>

        @if (count($errors) > 0)
            <div class="alert alert-danger" role="alert">
                <ul>
                    @foreach($errors->all() as $error)
                        <li>{{$error}}</li>
                    @endforeach
                </ul>
            </div>
        @endif
    </div>

@stop

resources/views/properties/index.blade.php
@extends('layouts.app')

@section('content')
    <div class="container-fluid">
        <h2 class="page-heading">Properties for sale</h2>
    @forelse($properties->chunk(4) as $chunk)
    <div class="row full-width-white">
        <div class="container">
            @foreach($chunk as $property)
                <div class="property-box col-md-3">
                    <a href="/properties/{{$property->id}}">
                        <div class="bg-fade">
                            <img src="../{!! $property->photos->first()['path'] !!}" alt="" class="fade-img property-img">
                        </div>
                        <p class="property-box-rd">{{$property->street}} {{$property->post}}</p>
                        <p class="property-box-price">&pound; {{number_format($property->price) }}</p>
                    </a>
                    <a href="#" class="btn btn-sm btn-default">{{$property->state}}</a>
                    @if($property->rightMove != '')
                        <a href="{{$property->rightMove}}" class="btn btn-primary pull-right">View on RightMove</a>
                    @endif

                </div>
            @endforeach
        </div>
    </div>
    @empty
        <div style="height: 330px">
            <h2 class="text-center">There are no properties found, please refine your search</h2>
        </div>
    @endforelse
    </div>
@stop

resources/views/properties/show.blade.php
@extends('layouts.app')

@section('content')

    <div class="container">
        @if(auth()->check())
            @if($property->rightMove == '' && !is_null($property->photos()))
                <a href="{{route('properties.rm', ['id' => $property->id])}}" class="btn btn-primary btn-lg">Send to RightMove</a>
            @else
                <a href="{{route('properties.rrm', ['id' => $property->id])}}" class="btn btn-danger btn-lg pull-right">Remove from Rightmove</a>
            @endif
        @endif
        <div class="row">
            <div class="col-md-4">
                    <div class="pull-right admin-controls">
                    @if(auth()->check())
                        <a href="{{route('properties.edit', ['id' => $property->id])}}" class="btn btn-warning"><i class="fa fa-pencil"></i> Edit</a>
                        <form action="{{route('properties.destroy', ['id' => $property->id])}}" method="POST">
                            {!! csrf_field() !!}
                            <input type="hidden" name="_method" value="delete">
                            <button type="submit" class="btn btn-danger"><i class="fa fa-times fa-fw"></i> Delete</button>
                        </form>
                    @elseif($property->rightMove != '')
                        <a href="{{$property->rightMove}}" class="btn btn-primary" style="margin-top: 0.5em;">View on right move</a>
                    @endif
                    </div>
                <h1>{!! $property->number !!} {!! $property->street!!}</h1>

                <h2 class="page-heading">&pound; {!! number_format($property->price) !!}</h2>

                <div class="description">
                    {!! nl2br($property->description) !!}
                </div>
            </div>

            <div class="col-md-8 property-disp-img">
                @foreach($property->photos->chunk(4) as $set)
                    <div class="row">
                        @foreach($set as $photo)
                            <div class="col-md-3">
                                @if(auth()->check())
                                    <form method="post" action="/photos/{{$photo->id}}">
                                        {!! csrf_field() !!}
                                        <input type="hidden" name="_method" value="DELETE">

                                        <button class="btn btn-primary" type="submit"><i class="fa fa-times"></i></button>
                                    </form>
                                @endif
                                <a href="{{asset($photo->path)}}" data-lightbox="gallery">
                                    <img src="{{asset($photo->thumbnail_path)}}" />
                                </a>
                            </div>
                        @endforeach
                    </div>
                @endforeach

                @if(auth()->check())
                <hr>

                <h2>Add Your Photos</h2>

                <form id="addPhotosForm" action="/properties/{{$property->id}}/photos" method="POST" class="dropzone">
                    {!! csrf_field() !!}
                </form>
                @endif
            </div>
        </div>
        <div class="row">
            <div class="col-md-8">
                @foreach($property->rooms->chunk(2) as $chunk)
                    <div class="row">
                        @foreach($chunk as $room)
                            <div class="col-md-4">
                                <h5>{{$room->name}}</h5>
                                <p>{{$room->desc}}</p>
                                <div>
                                    <p>Width: {{$room->width}} {{$room->unit}}</p>
                                    <p>Length: {{$room->length}} {{$room->unit}}</p>
                                </div>
                            </div>
                        @endforeach
                    </div>
                @endforeach
            </div>
        </div>
    </div>


@endsection

@section('scripts')
    <script>
        Dropzone.options.addPhotosForm = {
            paramName: 'photo',
            maxFileSize: 10,
            acceptedFiles: '.jpg, .jpeg, .png, .bmp'
        };
    </script>
@endsection